name: Update RT API Data
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: Update RT API Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python main.py
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data Updated
