name: Update Rooster Teeth Data
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: Update Rooster Teeth Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python -u update_rt.py
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Rooster Teeth Data
      - name: Upload to Internet Archive
        uses: shiruken/internet-archive-upload@8717da3a09626b59b7478994a1ce6837e9c7831d
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: roosterteeth-api
          files: api
