name: Identify Dark Uploads
on:
  schedule:
    - cron: '45 0 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: Identify Dark Uploads
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python -u update_archive_dark.py
      - name: Update Repository
        run: git pull
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Dark Uploads
